<link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/bootstrap.min.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/owl.carousel.min.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/slicknav.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/animate.min.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/price_rangs.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/magnific-popup.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/fontawesome-all.min.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/themify-icons.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/slick.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/nice-select.css'}}">
  <link rel="stylesheet" href="{{PUBLIC_URL .'assets/css/style.css'}}">